add --quiet option

diff --git a/cloudflare b/cloudflare
--- a/cloudflare
+++ b/cloudflare
@@ -2,6 +2,7 @@
 
 debug=0
 details=0
+quiet=0
 NL=$'\n'
 TA=$'\t'
 APIv4_ENDPOINT=https://api.cloudflare.com/client/v4
@@ -10,6 +11,7 @@ usage_text=\
 Options:
  --details, -d    Display detailed info where possible
  --debug, -D      Display API debugging info
+ --quiet, -q      Less verbose
  -E <email>
  -T <api_token>
 Environment variables:
@@ -20,7 +22,10 @@ Enter \"cloudflare help\" to list available commands."
 
 die()
 {
-	echo "$1" >&2
+	if [ -n "$1" ]
+	then
+		echo "$1" >&2
+	fi
 	exit ${2:-1}
 }
 
@@ -32,6 +37,10 @@ fi
 is_debug()
 {
 	[ "$debug" = 1 ]
+}
+is_quiet()
+{
+	[ "$quiet" = 1 ]
 }
 
 is_integer()
@@ -369,8 +378,8 @@ findout_record()
 	local zname_zid
 	local zid
 	local test_record
-	zone_id=
-	echo -n "Searching zone ... " >&2
+	zone_id=''
+	is_quiet || echo -n "Searching zone ... " >&2
 	
 	for zname_zid in `call_cf_v4 GET /zones -- .result %"%s:%s$NL" ,name,id`
 	do
@@ -384,8 +393,8 @@ findout_record()
 			break
 		fi
 	done
-	[ -z "$zone_id" ] && { echo >&2; return 2; }
-	echo -n "$zone, searching record ... " >&2
+	[ -z "$zone_id" ] && { is_quiet || echo >&2; return 2; }
+	is_quiet || echo -n "$zone, searching record ... " >&2
 	
 	rec_found=0
 	oldIFS=$IFS
@@ -399,7 +408,7 @@ findout_record()
 			if [ -z "$record_type" -o "$2" = "$record_type" ]
 			then
 				let rec_found++
-				[ $rec_found -gt 1 ] && { echo >&2; return 4; }
+				[ $rec_found -gt 1 ] && { is_quiet || echo >&2; return 4; }
 				
 				shift
 				record_type=$1
@@ -420,7 +429,7 @@ findout_record()
 	done
 	IFS=$oldIFS
 	
-	echo "$record_id" >&2
+	is_quiet || echo "$record_id" >&2
 	[ -z "$record_id" ] && return 3
 	
 	return 0
@@ -449,6 +458,8 @@ do
 		debug=1;;
 	-d|--detail|--detailed|--details)
 		details=1;;
+	-q|--quiet)
+		quiet=1;;
 	-h|--help)
 		die "$usage_text" 0
 		;;
@@ -577,7 +588,7 @@ add)
 			call_cf_v4 POST /zones/$zone_id/dns_records type="$type" name="$name" content="$content" ttl="$ttl" priority="$prio"
 			;;
 		LOC)
-			locdata=
+			locdata=''
 			data_separated=1
 			if [ -n "${content//[! ]/}" ]
 			then
@@ -627,7 +638,7 @@ add)
 		
 	whitelist|blacklist|block|challenge)
 		trg=$1
-		trg_type=
+		trg_type=''
 		shift
 		notes=$*
 		case "$cmd2" in
@@ -690,7 +701,7 @@ delete)
 			record_id=$prm2
 		
 		else
-			record_type=
+			record_type=''
 			first_match=0
 			
 			[ -z "$prm1" ] && die "Usage: cloudflare delete record [<record-name> [<type> | first] | [<zone-name>|<zone-id>] <record-id>]"
@@ -763,7 +774,7 @@ change|set)
 Other: see output of 'show zone' command"
 		get_zone_id "$1"
 		shift
-		setting_items=
+		setting_items=''
 		
 		declare -A map
 		map[sec_lvl]=security_level
@@ -819,7 +830,7 @@ Settings:
 		[ -z "$1" ] && die "$str1"
 		record_name=$1
 		shift
-		record_type=
+		record_type=''
 		first_match=0
 		
 		while [ -n "$1" ]
@@ -842,14 +853,14 @@ Settings:
 		case $e in
 		0)	true;;
 		2)	die "No suitable DNS zone found for \`$record_name'";;
-		3)	die "DNS record \`$record_name' not found";;
+		3)	is_quiet && die || die "DNS record \`$record_name' not found";;
 		4)	die "Ambiguous record name: \`$record_name'";;
 		*)	die "Internal error";;
 		esac
 		
 		record_content_esc=${record_content//\"/\\\"}
 		old_data="\"name\":\"$record_name\",\"type\":\"$record_type\",\"ttl\":$record_ttl,\"content\":\"$record_content_esc\""
-		new_data=
+		new_data=''
 		while [ -n "$1" ]
 		do
 			setting=$1
@@ -918,8 +929,8 @@ check)
 invalidate)
 	if [ -n "$1" ]
 	then
-		urls=
-		zone_id=
+		urls=''
+		zone_id=''
 		for url in "$@"
 		do
 			urls="${urls:+$urls,}\"$url\""
