new subcommand: invalidate - invalidate individual URLs in cache

diff --git a/cloudflare b/cloudflare
--- a/cloudflare
+++ b/cloudflare
@@ -1,10 +1,9 @@
 #!/bin/bash
 
 declare -A opts
-do_export=0
-NL='
-'
-TA='	'
+verbose=0
+NL=$'\n'
+TA=$'\t'
 APIv1_ENDPOINT=https://www.cloudflare.com/api_json.html
 APIv4_ENDPOINT=https://api.cloudflare.com/client/v4
 usage_text="Usage: cloudflare [-v] [-E <email>] [-T <api_token>] <command> <parameters>
@@ -18,6 +17,11 @@ die()
 {
 	echo "$1" >&2
 	exit ${2:-1}
+}
+
+is_verbose()
+{
+	[ "$verbose" = 1 ]
 }
 
 is_integer()
@@ -55,30 +59,46 @@ call_cf()
 
 call_cf_v4()
 {
-	local method=$1
-	local formtype=data
+	local method path formtype
+	method=${1^^}
 	shift
-	local path=$1
+	path=$1
 	shift
+	formtype=data
 	declare -a curl_opts
 	curl_opts=()
 	if [ "$method" = POST ]
 	then
 		formtype=form
-	else
-		curl_opts+=(-H "Content-Type: application/json" -G)
 	fi
+	if [ "$method" != POST ]
+	then
+		curl_opts+=(-H "Content-Type: application/json")
+	fi
+	if [ "$method" != POST -a "$method" != DELETE ]
+	then
+		curl_opts+=(-G)
+	fi
+
 	while [ -n "$1" ]
 	do
 		if [ ."$1" = .-- ]
 		then
 			shift
+			if [ -z "$1" ]
+			then
+				set -- '&?success?"success"?"failed"'
+			fi
 			break
 		else
 			curl_opts+=(--$formtype "$1")
 		fi
 		shift
 	done
+	if is_verbose
+	then
+		echo "<<< curl -X $method ${curl_opts[*]} $APIv4_ENDPOINT$path" >&2
+	fi
 	curl -sS -H "X-Auth-Email: $CF_ACCOUNT" -H "X-Auth-Key: $CF_TOKEN" \
 		-X "$method" "${curl_opts[@]}" \
 		"$APIv4_ENDPOINT$path" | json_decode "$@"
@@ -136,7 +156,7 @@ json_decode()
 		}
 
 		$data0 = json_decode(file_get_contents("php://stdin"), 1);
-		if('$do_export') file_put_contents("php://stderr", var_export($data0, 1));
+		if('$verbose') file_put_contents("php://stderr", var_export($data0, 1));
 		if($data0["result"] == "error")
 		{
 			echo $data0["msg"] . "\n";
@@ -334,7 +354,7 @@ do
 		CF_ACCOUNT=$1;;
 	-T)	shift
 		CF_TOKEN=$1;;
-	-v)	do_export=1;;
+	-v)	verbose=1;;
 	-h|--help)
 		die "$usage_text" 0
 		;;
@@ -535,7 +555,7 @@ delete)
 			die "Usage: cloudflare delete zone <name>"
 		fi
 		get_zone_id "$1"
-		call_cf_v4 DELETE /zones/$zone_id -- '&?success?"success"?"failed"'
+		call_cf_v4 DELETE /zones/$zone_id
 		;;
 	*)
 		die "Parameters:
@@ -698,13 +718,54 @@ check)
 		shift
 		[ -z "$1" ] && die "Usage: cloudflare check zone <zone>"
 		get_zone_id "$1"
-		call_cf_v4 PUT /zones/$zone_id/activation_check -- '&?success?"success"?"failed"'
+		call_cf_v4 PUT /zones/$zone_id/activation_check
 		;;
 	*)
 		die "Parameters:
    zone"
 		;;
 	esac
+	;;
+
+invalidate)
+	if [ -n "$1" ]
+	then
+		urls=
+		zone_id=
+		for url in "$@"
+		do
+			urls="${urls:+,}\"$url\""
+			if [ -z "$zone_id" ]
+			then
+				if [[ "$url" =~ ^([^:]+:)?/*([^:/]+) ]]
+				then
+					re_grps=${#BASH_REMATCH[@]}
+					domain=${BASH_REMATCH[re_grps-1]}
+					while true
+					do
+						zone_id=`get_zone_id "$domain" 2>/dev/null; echo "$zone_id"`
+						if [ -n "$zone_id" ]
+						then
+							break
+						fi
+						parent=${domain#*.}
+						if [ "$parent" = "$domain" ]
+						then
+							break
+						fi
+						domain=$parent
+					done
+				fi
+			fi
+		done
+		if [ -z "$zone_id" ]
+		then
+			die "Zone name could not figured out."
+		fi
+		call_cf_v4 DELETE /zones/$zone_id/purge_cache "{\"files\":[$urls]}"
+	else
+		die "Usage: cloudflare invalidate <url-1> [url-2 [url-3 [...]]]"
+	fi
 	;;
 	
 json)
@@ -713,7 +774,7 @@ json)
 	
 *|help)
 	die "Commands:
-   show, add, delete, set, clear, check"
+   show, add, delete, set, clear, invalidate check"
 	;;
 esac
 
